### ISSUE TITLE
Move non-core openwrt recipes out of recipes-core

### ISSUE THREAD

**Issue by troth** [kraj/meta-openwrt#11]
The recipes-core directory should probably only be for recipes for packages that are available in the OpenWRT/LEDE core git repo and recipes to build an image similar to what can be built with OpenWRT/LEDE proper.

Move non-core recipes out of recipes-core into a new recipes-extended directory. For example, the juci recipes.

From discussion with Khem at ELC-NA 2017.

**Comment by cshoredaniel** [comment]
Actually there is a bunch of stuff in core that isn't used in normal images either (like mountd).  These probably also ought to be divided out.
