### ISSUE TITLE
avoid copying files from upstream openwrt

### ISSUE THREAD

**Issue by troth** [kraj/meta-openwrt#13]
In the current meta-openwrt, files have been copied verbatim from the upstream openwrt into meta-openwrt recipe file directories for various packages. The was done to expedite getting a base image up and booting, but will caused a maintenance burden in the future as upstream evolves.

Ideally, cloning the upstream openwrt git repo once and populating a staging sysroot which can be used by individual recipes should reduce having multiple clones of upstream to one and that one being shared across meta-openwrt recipes.

Khem suggested looking into how various gcc recipes within oe-core share a single git repo clone to accomplish this. Khem had some other possible solution ideas if the gcc approach doesn't work out.

Once a single, shared copy of the upstream openwrt repo is staged, individual recipes can pull relevant files and patches from there into a package's sysroot or build area respectively. This would remove the need to maintain copies of the files in meta-openwrt.

From discussions with Khem at ELC-NA 2017.

**Comment by cshoredaniel** [comment]
This has been resolved by #40
