### ISSUE TITLE
No recipe in default for busybox_1.34

### ISSUE THREAD

**Issue by frebour1** [kraj/meta-openwrt#131]
Following wiki , building openwrt-image-minimal I got :

$ TCLIBC=musl MACHINE=qemuarm bitbake openwrt-image-base
Loading cache: 100% |#########################################################################################| Time: 0:00:01
Loaded 3854 entries from dependency cache.
**ERROR: No recipes in default available for:
  /mnt/yocto/openembedded-core/meta-openwrt/recipes-tweaks/busybox/busybox_1.34.%.bbappend**

**Comment by coolmaxter** [comment]
Hi, did you solve the problem? I just got the same issue here.

**Comment by frebour1** [comment]
I have delete following files :
recipes-tweaks/busybox/busybox_1.34.%.bbappend

**Comment by kmwegger** [comment]
The best way to solve this is to add the bbappend to `BBMASK` in your `local.conf` or similar.
```
BBMASK = "recipes-tweaks/busybox/busybox_1.34.%.bbappend"
```

Using `BBMASK` you can use the layer normally, without forking or manually deleting files.
