### ISSUE TITLE
Bump to 22.03

### ISSUE THREAD

**Issue by nquest** [kraj/meta-openwrt#132]
Hello!
I started bumping versions of all packages to 22.03.
Are there any further plans to implement base-files as a separate package? Now many packages download full OpenWRT tree.

**Comment by kraj** [comment]
It was ok all until now but if we need full tree then perhaps it might make sense to do it once and share it with multiple recipes

**Comment by nquest** [comment]
Oh, sorry, maybe I broke something in build system, but for all recipes which uses openwrt-base-files SRC_URI to main openwrt repo was added. Trying to fix.

**Comment by nquest** [comment]
Ok, almost done, please see PR #133
