### ISSUE TITLE
general question - how is this different from original openwrt

### ISSUE THREAD

**Issue by laoshaw** [kraj/meta-openwrt#136]
what's the goal of this project? how is it different from tne original openwrt? when should I use this?

sorry I could not find a better place to ask dumb questions like this one.

Thanks.

**Comment by kraj** [comment]
@laoshaw the purpose is to provide openWRT packages ( e.g. luci etc. ) on Yocto based systems. Since lot of folks might be interested in including some openWRT components into their products which are built using yocto project. Hope that helps.
