### ISSUE TITLE
general question - Is there anyway to add snort3 in this?

### ISSUE THREAD

**Issue by RNGesus-exe** [kraj/meta-openwrt#140]
I want to enable NIDS (snort3) in meta-openwrt, Can someone explain how to add it. Couldn't find a better place to ask this.

**Comment by kraj** [comment]
I think you need to first add recipe for snort3, which might be doable easily by looking at some other app recipes in meta-openwrt. e.g `./recipes-support/lua-socket/lua-socket_git.bb`

**Comment by RNGesus-exe** [comment]
I was wondering, why isn't Snort3 already a part of the community-supported packages in meta-openwrt? Is there a specific reason it hasn't been included so far?

**Comment by kraj** [comment]
> I was wondering, why isn't Snort3 already a part of the community-supported packages in meta-openwrt? Is there a specific reason it hasn't been included so far?

right, no one added it so far.

**Comment by kraj** [comment]
If the recipe depends on meta-openwrt then send a PR here

**Comment by RNGesus-exe** [comment]
I sent a PR of the recipe to meta-openembedded

**Comment by RNGesus-exe** [comment]
Closed this issue as snort3 has been added to meta-openembedded master branch with this [PR](https://github.com/openembedded/meta-openembedded/pull/789)
