### ISSUE TITLE
libblobpack does not accept cflags

### ISSUE THREAD

**Issue by muvarov** [kraj/meta-openwrt#20]
That does not work on OE for some reason:
libblobpack/git-r0/git/Makefile
<pre>
CFLAGS+=-g -Werror -Wall -Wno-unused-function -std=gnu99 -fPIC
%.o: %.c 
	$(CC)  $(CFLAGS) -c -o $@ $^
</pre>

Changed that following to make ti compile:
<pre>
MYCFLAGS+=-g -Werror -Wall -Wno-unused-function -std=gnu99 -fPIC
%.o: %.c 
	$(CC) $(MYCFLAGS) $(CFLAGS) -c -o $@ $^
</pre>

**Comment by kraj** [comment]
can you make a patch and submit it upstream as well
