### ISSUE TITLE
fix README.md instructions to get working openwrt system

### ISSUE THREAD

**Issue by milksob** [kraj/meta-openwrt#23]
Following current instruction from README doesn't result in working image (I tried qemux86) with web interface and other features.

"libubox-examples" gives nothing
"juci" -- error while build

**Comment by kraj** [comment]
Please send a pull and I will accept it

**Comment by milksob** [comment]
I'll be happy to send pull request as soon as I get openwrt from this
layers myself ;-)


2018-01-17 6:29 GMT+03:00 Khem Raj <notifications@github.com>:

**Comment by cshoredaniel** [comment]
@milksob You might want to try with a fresh pull and reading the updated README!

**Comment by cshoredaniel** [comment]
@milksob if you try using oe-core master or rocko, you may need to revert oe-core commit 7267e7c000c76c44d09835d4cd2bc485b6a39a2a to be able to add layers; there seems to be some funkiness with bitbake add-layers with that commit, but it seems to be not to be an issue for all users, but some do see it.

**Comment by milksob** [comment]
thx! I'll check as soon as I get some time
