### ISSUE TITLE
Figuring out the nodistro thing v. procd

### ISSUE THREAD

**Issue by cshoredaniel** [kraj/meta-openwrt#30]
I've noticed that if one sets even DISTRO_FEATURES += "procd" that glibc complains about locales, because it no longer has DISTRO_FEATURES_LIBC in the DISTRO_FEATURES.

Another complication may be: DISTRO_FEATURES_BACKFILL_CONSIDERED_append = "sysvinit systemd" which is also because of procd.

I'm wondering the best way to handle this, since I'd like to keep this working with the nodistro case, without special requirements in the conf/local.conf.  The obvious thing would be to drop the DISTRO_FEATURES requirement in the procd recipe, but I'm not sure that's appropriate since it's an init_manager & dev_manager like systemd.

**Comment by kraj** [comment]
procd should be treated as replacement for system init be it syvinit or systemd. DISTRO_FEATURES_append = " procd" might be ok to use.
