### ISSUE TITLE
firewall3 needs to depend on appropriate kernel modules

### ISSUE THREAD

**Issue by cshoredaniel** [kraj/meta-openwrt#35]
firewall3 has some hard requirements for kernel modules for it to do anything, so need to add dependencies and module loading hints (e.g /etc/modules.d/x for kmodloader /etc/modules-load.d/x.conf for sysvinit and systemd).

**Comment by kraj** [comment]
Adding that to RDEPENDS_${PN} would be the soluton. Care to submit a patch ?
