### ISSUE TITLE
Is "BSD" okay for BSD 1 Clause license?

### ISSUE THREAD

**Issue by cshoredaniel** [kraj/meta-openwrt#58]
jsonpath has a BSD 1 Clause license; is it okay to leave it as "BSD" or does it need to be updated to "BSD-1-Clause" SPDX?

**Comment by kraj** [comment]
yes it should be updated to SPDX convention BSD-1-Clause

http://git.openembedded.org/openembedded-core/tree/meta/files/common-licenses/BSD-1-Clause
