### ISSUE TITLE
Remove Juci?

### ISSUE THREAD

**Issue by cshoredaniel** [kraj/meta-openwrt#61]
Current Juci is on a git rev that looks like it never worked, and current stable Juci depends on a custom lighttpd build, with changes which upstream lightpd is unlikely to incorporate (according to the lighttpd devs).  I think it's even more niche than openwrt and luci and think we'd be better off pursuing luci in the short term.  Long term I'm personally more interested in something suitable as a hybrid with regular OE rather than an openwrt-specific thing like https://github.com/jow-/luci-ng or juci.

**Comment by kraj** [comment]
I agree. it was seeming to be a good UI back then but it never worked so send a pull
