### ISSUE TITLE
ipset recipe should point to http://ftp.netfilter.org/pub/ipset/

### ISSUE THREAD

**Issue by kraj** [kraj/meta-openwrt#69]
this is because the current recipe SRC_URI location only handles latest release of ipset.

**Comment by cshoredaniel** [comment]
I noticed that OE doesn't build kernel-module-ipt-ipset by default, which makes ipset recipe useless.  Is there a way to enable a kernel fragment from another recipe (e.g. the ipset recipe) so that if ipset is built the ipset kernel module is built?

**Comment by kraj** [comment]
I think you can create a rdep on the module and then force a build error when someone build ipset.

**Comment by cshoredaniel** [comment]
Ok, so not trying to solve the issue without intervention but making it obvious so the user takes care of it?

**Comment by kraj** [comment]
right

**Comment by kraj** [comment]
Fixed now
